apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: productpage
spec:
  host: productpage
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: productpage
spec:
  hosts:
  - productpage
  http:
  - fault:
      delay:
        percent: 100
        fixedDelay: 47s
    route:
    - destination:
        host: productpage
        subset: v2
    timeout: 4.5s
  - route:
    - destination:
        host: productpage
        subset: v1
